### ISSUE TITLE
Payments in foreign currency

### ISSUE THREAD

**Issue by Sha-yol** [adyanth/splitwise-firefly-sync#10]
FF does not convert automatically between currencies, so requires adding both amount in foreign and native currency.
What happens if the sync tries to add a SW expense in a non-native currency?
I suggest the following should happen:
- If SW expense stores the share in both native and foreign currencies (using estimated conversion rate), fill in both of those values.
- If not, fill in a a dummy value in the native currency (0.00001)
- In both cases, add some tag for manual revision later on

Another complication, which I think isn't handled right now: "native" and "foreign" is defined in SW at the user level, but on FF it is defined at the asset account level. So when adding a txn, should check whether the SW expense currency is native/foreign for the FF source account.

**Comment by Sha-yol** [comment]
Note: if manually revising on FF, need to resolve #4.

**Comment by adyanth** [comment]
Adding estimated conversion rates would require an additional (potentially paid) API to be interfaced with. Since both would need manual revision (because who is paying the exact exchange rate anyway), adding a dummy value with a custom tag sounds good to me.

The SW user's native currency should not matter, since each transaction would be in a specific currency at the end. But the FF asset account's native currency is the one to be handled correctly.

**Comment by Sha-yol** [comment]
Agree it's not needed to add an estimated conversion rate with an additional API.
So the process should be:
- Check if the SW currency matches the FF account native currency. As you said, we can check it at the individual txn level, so no conflict with SW currency.
- If it doesn't, fill a dummy value for the native currency, fill the SW value in the foreign currency, and add a "fixme/currency" tag or something.
Sounds good? If so, I'll get to work on it :)

**Comment by adyanth** [comment]
Fixed by https://github.com/adyanth/splitwise-firefly-sync/pull/13
